# Generated by Django 4.2.4 on 2023-09-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_img_post_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
        migrations.AddField(
            model_name='post',
            name='pimage',
            field=models.ImageField(null=True, upload_to='post_image'),
        ),
    ]
